### ISSUE TITLE
no such table: student_management_app_courses

### ISSUE THREAD

**Issue by hammadarshad1** [hackstarsj/student_management_system_in_django#1]
I am getting this error when migrating the project

**Comment by abdulaibratokamara** [comment]
no such table: student_management_app_courses #1.
This is the error am getting whenever I try to migrate.

**Comment by hackstarsj** [comment]
Surround your course part in try except block in forms.py

**Comment by hammadarshad1** [comment]
can you please resolve this error! that we are getting?

**Comment by hackstarsj** [comment]
Ok

**Comment by hackstarsj** [comment]
Check this project latest part after 10 i fixed it already
