### ISSUE TITLE
Issue while creating CUSTOM USER

### ISSUE THREAD

**Issue by ayushnanda21** [hackstarsj/student_management_system_in_django#2]
I have defined : AUTH_USER_MODEL="my_app_name.CustomUser"  in settings.py
In models.py : custom user class.
applied migrations
But getting different errors which are not resolved. Could anyone help ?

I have attached errors below.

![image](https://user-images.githubusercontent.com/64643319/101448193-a268b180-394c-11eb-99e8-342e3c3de8ec.png)

**Comment by hammadarshad1** [comment]
I something notice about the Bad URL: why its "https|" instead of "https:"

**Comment by ayushnanda21** [comment]
I removed {% static %} from my templating file https of googlefonts and its showing this now. I guess resolved?
![image](https://user-images.githubusercontent.com/64643319/101449845-89153480-394f-11eb-8756-6caf408a6728.png)

**Comment by hammadarshad1** [comment]
> I removed {% static %} from my templating file https of googlefonts and its showing this now. I guess resolved?
> ![image](https://user-images.githubusercontent.com/64643319/101449845-89153480-394f-11eb-8756-6caf408a6728.png)

that's great!

**Comment by ayushnanda21** [comment]
While creating superuser its' stucked
![image](https://user-images.githubusercontent.com/64643319/101451791-bf07e800-3952-11eb-9ff0-9505d1c77d4e.png)

**Comment by hammadarshad1** [comment]
> While creating superuser its' stucked
> ![image](https://user-images.githubusercontent.com/64643319/101451791-bf07e800-3952-11eb-9ff0-9505d1c77d4e.png)

you need to migrate first

**Comment by ayushnanda21** [comment]
![image](https://user-images.githubusercontent.com/64643319/101456556-3e4cea00-395a-11eb-9a89-1f3818ca5267.png)

**Comment by hammadarshad1** [comment]
did you create a database in mysql?

**Comment by olamyk** [comment]
please can someone help me with this error am running through, i get this in my first migrations
![IMG_20210730_134724_5 1](https://user-images.githubusercontent.com/88193400/127655274-6f0d268c-bcb7-4fa3-b74f-ba2133c5f2b5.jpg)

**Comment by AkshayGaikwad02** [comment]
sir your rediment project i was extracted and after that i am run that on cmd and it's showing table doesn't exit....

**Comment by AkshayGaikwad02** [comment]
can you please solve this problem

**Comment by hackstarsj** [comment]
> please can someone help me with this error am running through, i get this in my first migrations ![IMG_20210730_134724_5 1](https://user-images.githubusercontent.com/88193400/127655274-6f0d268c-bcb7-4fa3-b74f-ba2133c5f2b5.jpg)

Correct the app name in settings for AUTH_USER_MODEL
