### ISSUE TITLE
Usage of @receiver(post_save, sender=CustomUser)

### ISSUE THREAD

**Issue by ayushnanda21** [hackstarsj/student_management_system_in_django#3]
As we know,
all this receiver will work when we add new data in custom user table after inserting it will insert current id of customuser into othertsable such as adminhod,staff,student

But this is the error and amy models.py
![image](https://user-images.githubusercontent.com/64643319/101595201-fc36ad80-3a18-11eb-803e-5d4b263cd100.png)

**Comment by ayushnanda21** [comment]
It occurs while creation of superusers in db

**Comment by hackstarsj** [comment]
You didn't add condition for different type of user type 1 2 3 see my code
